// モデルカタログデータ
// 主要なOllamaモデルの詳細情報を事前定義

use crate::database::models::ModelCatalog;

/// 主要なOllamaモデルの詳細情報を取得
pub fn get_predefined_model_catalog() -> Vec<ModelCatalog> {
    let now = chrono::Utc::now();
    
    vec![
        // Llama 3 シリーズ
        ModelCatalog {
            name: "llama3".to_string(),
            description: Some("Meta Llama 3 - 最新の大規模言語モデル。高品質なテキスト生成と推論能力を提供します。".to_string()),
            size: Some(4_700_000_000), // 約4.7GB
            parameters: Some(8_000_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("Meta".to_string()),
            license: Some("Llama 3 Community License".to_string()),
            tags: Some(r#"["chat", "general", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "llama3:8b".to_string(),
            description: Some("Meta Llama 3 8B - 8Bパラメータ版。バランスの取れた性能と効率を提供します。".to_string()),
            size: Some(4_700_000_000),
            parameters: Some(8_000_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("Meta".to_string()),
            license: Some("Llama 3 Community License".to_string()),
            tags: Some(r#"["chat", "general", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "llama3:70b".to_string(),
            description: Some("Meta Llama 3 70B - 70Bパラメータ版。最高レベルの性能を提供します。".to_string()),
            size: Some(40_000_000_000),
            parameters: Some(70_000_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("Meta".to_string()),
            license: Some("Llama 3 Community License".to_string()),
            tags: Some(r#"["chat", "general", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        
        // Mistral シリーズ
        ModelCatalog {
            name: "mistral".to_string(),
            description: Some("Mistral 7B - 高性能なオープンソース言語モデル。効率的で高品質なテキスト生成を提供します。".to_string()),
            size: Some(4_100_000_000),
            parameters: Some(7_000_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("Mistral AI".to_string()),
            license: Some("Apache 2.0".to_string()),
            tags: Some(r#"["chat", "general", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "mistral:7b".to_string(),
            description: Some("Mistral 7B - 7Bパラメータ版。効率的で高品質なテキスト生成を提供します。".to_string()),
            size: Some(4_100_000_000),
            parameters: Some(7_000_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("Mistral AI".to_string()),
            license: Some("Apache 2.0".to_string()),
            tags: Some(r#"["chat", "general", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        
        // CodeLlama シリーズ
        ModelCatalog {
            name: "codellama".to_string(),
            description: Some("CodeLlama - コード生成とプログラミング支援に特化したモデル。".to_string()),
            size: Some(3_800_000_000),
            parameters: Some(7_000_000_000),
            category: Some("code".to_string()),
            recommended: true,
            author: Some("Meta".to_string()),
            license: Some("Llama 2 Community License".to_string()),
            tags: Some(r#"["code", "programming", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "codellama:7b".to_string(),
            description: Some("CodeLlama 7B - コード生成に特化した7Bパラメータ版。".to_string()),
            size: Some(3_800_000_000),
            parameters: Some(7_000_000_000),
            category: Some("code".to_string()),
            recommended: true,
            author: Some("Meta".to_string()),
            license: Some("Llama 2 Community License".to_string()),
            tags: Some(r#"["code", "programming", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "codellama:13b".to_string(),
            description: Some("CodeLlama 13B - コード生成に特化した13Bパラメータ版。".to_string()),
            size: Some(7_300_000_000),
            parameters: Some(13_000_000_000),
            category: Some("code".to_string()),
            recommended: true,
            author: Some("Meta".to_string()),
            license: Some("Llama 2 Community License".to_string()),
            tags: Some(r#"["code", "programming", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "codellama:34b".to_string(),
            description: Some("CodeLlama 34B - コード生成に特化した34Bパラメータ版。最高レベルのコード生成能力を提供します。".to_string()),
            size: Some(19_000_000_000),
            parameters: Some(34_000_000_000),
            category: Some("code".to_string()),
            recommended: true,
            author: Some("Meta".to_string()),
            license: Some("Llama 2 Community License".to_string()),
            tags: Some(r#"["code", "programming", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        
        // Phi-3 シリーズ
        ModelCatalog {
            name: "phi3".to_string(),
            description: Some("Phi-3 - 軽量で高性能な小規模モデル。モバイルデバイスでも動作可能です。".to_string()),
            size: Some(2_200_000_000),
            parameters: Some(3_800_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("Microsoft".to_string()),
            license: Some("MIT".to_string()),
            tags: Some(r#"["chat", "general", "lightweight", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "phi3:mini".to_string(),
            description: Some("Phi-3 Mini - 最小サイズのPhi-3モデル。高速で効率的です。".to_string()),
            size: Some(2_200_000_000),
            parameters: Some(3_800_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("Microsoft".to_string()),
            license: Some("MIT".to_string()),
            tags: Some(r#"["chat", "general", "lightweight", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        
        // Llama 2 シリーズ
        ModelCatalog {
            name: "llama2".to_string(),
            description: Some("Meta Llama 2 - 高性能な大規模言語モデル。汎用的なテキスト生成タスクに適しています。".to_string()),
            size: Some(3_800_000_000),
            parameters: Some(7_000_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("Meta".to_string()),
            license: Some("Llama 2 Community License".to_string()),
            tags: Some(r#"["chat", "general", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "llama2:7b".to_string(),
            description: Some("Meta Llama 2 7B - 7Bパラメータ版。バランスの取れた性能を提供します。".to_string()),
            size: Some(3_800_000_000),
            parameters: Some(7_000_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("Meta".to_string()),
            license: Some("Llama 2 Community License".to_string()),
            tags: Some(r#"["chat", "general", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "llama2:13b".to_string(),
            description: Some("Meta Llama 2 13B - 13Bパラメータ版。より高い性能を提供します。".to_string()),
            size: Some(7_300_000_000),
            parameters: Some(13_000_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("Meta".to_string()),
            license: Some("Llama 2 Community License".to_string()),
            tags: Some(r#"["chat", "general", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        
        // Gemma シリーズ
        ModelCatalog {
            name: "gemma".to_string(),
            description: Some("Google Gemma - Googleが開発した軽量で高性能なオープンソースモデル。".to_string()),
            size: Some(2_000_000_000),
            parameters: Some(2_000_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("Google".to_string()),
            license: Some("Gemma Terms of Use".to_string()),
            tags: Some(r#"["chat", "general", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "gemma:2b".to_string(),
            description: Some("Google Gemma 2B - 2Bパラメータ版。軽量で高速です。".to_string()),
            size: Some(2_000_000_000),
            parameters: Some(2_000_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("Google".to_string()),
            license: Some("Gemma Terms of Use".to_string()),
            tags: Some(r#"["chat", "general", "lightweight", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "gemma:7b".to_string(),
            description: Some("Google Gemma 7B - 7Bパラメータ版。より高い性能を提供します。".to_string()),
            size: Some(4_500_000_000),
            parameters: Some(7_000_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("Google".to_string()),
            license: Some("Gemma Terms of Use".to_string()),
            tags: Some(r#"["chat", "general", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        
        // Neural Chat シリーズ
        ModelCatalog {
            name: "neural-chat".to_string(),
            description: Some("Neural Chat - 会話に最適化されたモデル。自然な対話を生成します。".to_string()),
            size: Some(4_100_000_000),
            parameters: Some(7_000_000_000),
            category: Some("chat".to_string()),
            recommended: false,
            author: Some("Intel".to_string()),
            license: Some("Apache 2.0".to_string()),
            tags: Some(r#"["chat", "conversation"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        
        // Starling シリーズ
        ModelCatalog {
            name: "starling-lm".to_string(),
            description: Some("Starling-LM - 強化学習で最適化された会話モデル。".to_string()),
            size: Some(4_100_000_000),
            parameters: Some(7_000_000_000),
            category: Some("chat".to_string()),
            recommended: false,
            author: Some("Berkeley Function Calling Leaderboard".to_string()),
            license: Some("CC-BY-NC-4.0".to_string()),
            tags: Some(r#"["chat", "conversation"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
    ]
}

