// モデルカタログデータ
// 主要なOllamaモデルの詳細情報を事前定義

use crate::database::models::ModelCatalog;

/// 主要なOllamaモデルの詳細情報を取得
pub fn get_predefined_model_catalog() -> Vec<ModelCatalog> {
    let now = chrono::Utc::now();
    
    vec![
        // Llama 3 シリーズ
        ModelCatalog {
            name: "llama3".to_string(),
            description: Some("Meta Llama 3 - 最新の大規模言語モデル。高品質なテキスト生成と推論能力を提供します。".to_string()),
            size: Some(4_700_000_000), // 約4.7GB
            parameters: Some(8_000_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("Meta".to_string()),
            license: Some("Llama 3 Community License".to_string()),
            tags: Some(r#"["chat", "general", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "llama3:8b".to_string(),
            description: Some("Meta Llama 3 8B - 8Bパラメータ版。バランスの取れた性能と効率を提供します。".to_string()),
            size: Some(4_700_000_000),
            parameters: Some(8_000_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("Meta".to_string()),
            license: Some("Llama 3 Community License".to_string()),
            tags: Some(r#"["chat", "general", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "llama3:70b".to_string(),
            description: Some("Meta Llama 3 70B - 70Bパラメータ版。最高レベルの性能を提供します。".to_string()),
            size: Some(40_000_000_000),
            parameters: Some(70_000_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("Meta".to_string()),
            license: Some("Llama 3 Community License".to_string()),
            tags: Some(r#"["chat", "general", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        
        // Mistral シリーズ
        ModelCatalog {
            name: "mistral".to_string(),
            description: Some("Mistral 7B - 高性能なオープンソース言語モデル。効率的で高品質なテキスト生成を提供します。".to_string()),
            size: Some(4_100_000_000),
            parameters: Some(7_000_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("Mistral AI".to_string()),
            license: Some("Apache 2.0".to_string()),
            tags: Some(r#"["chat", "general", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "mistral:7b".to_string(),
            description: Some("Mistral 7B - 7Bパラメータ版。効率的で高品質なテキスト生成を提供します。".to_string()),
            size: Some(4_100_000_000),
            parameters: Some(7_000_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("Mistral AI".to_string()),
            license: Some("Apache 2.0".to_string()),
            tags: Some(r#"["chat", "general", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        
        // CodeLlama シリーズ
        ModelCatalog {
            name: "codellama".to_string(),
            description: Some("CodeLlama - コード生成とプログラミング支援に特化したモデル。".to_string()),
            size: Some(3_800_000_000),
            parameters: Some(7_000_000_000),
            category: Some("code".to_string()),
            recommended: true,
            author: Some("Meta".to_string()),
            license: Some("Llama 2 Community License".to_string()),
            tags: Some(r#"["code", "programming", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "codellama:7b".to_string(),
            description: Some("CodeLlama 7B - コード生成に特化した7Bパラメータ版。".to_string()),
            size: Some(3_800_000_000),
            parameters: Some(7_000_000_000),
            category: Some("code".to_string()),
            recommended: true,
            author: Some("Meta".to_string()),
            license: Some("Llama 2 Community License".to_string()),
            tags: Some(r#"["code", "programming", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "codellama:13b".to_string(),
            description: Some("CodeLlama 13B - コード生成に特化した13Bパラメータ版。".to_string()),
            size: Some(7_300_000_000),
            parameters: Some(13_000_000_000),
            category: Some("code".to_string()),
            recommended: true,
            author: Some("Meta".to_string()),
            license: Some("Llama 2 Community License".to_string()),
            tags: Some(r#"["code", "programming", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "codellama:34b".to_string(),
            description: Some("CodeLlama 34B - コード生成に特化した34Bパラメータ版。最高レベルのコード生成能力を提供します。".to_string()),
            size: Some(19_000_000_000),
            parameters: Some(34_000_000_000),
            category: Some("code".to_string()),
            recommended: true,
            author: Some("Meta".to_string()),
            license: Some("Llama 2 Community License".to_string()),
            tags: Some(r#"["code", "programming", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        
        // Phi-3 シリーズ
        ModelCatalog {
            name: "phi3".to_string(),
            description: Some("Phi-3 - 軽量で高性能な小規模モデル。モバイルデバイスでも動作可能です。".to_string()),
            size: Some(2_200_000_000),
            parameters: Some(3_800_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("Microsoft".to_string()),
            license: Some("MIT".to_string()),
            tags: Some(r#"["chat", "general", "lightweight", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "phi3:mini".to_string(),
            description: Some("Phi-3 Mini - 最小サイズのPhi-3モデル。高速で効率的です。".to_string()),
            size: Some(2_200_000_000),
            parameters: Some(3_800_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("Microsoft".to_string()),
            license: Some("MIT".to_string()),
            tags: Some(r#"["chat", "general", "lightweight", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        
        // Llama 2 シリーズ
        ModelCatalog {
            name: "llama2".to_string(),
            description: Some("Meta Llama 2 - 高性能な大規模言語モデル。汎用的なテキスト生成タスクに適しています。".to_string()),
            size: Some(3_800_000_000),
            parameters: Some(7_000_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("Meta".to_string()),
            license: Some("Llama 2 Community License".to_string()),
            tags: Some(r#"["chat", "general", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "llama2:7b".to_string(),
            description: Some("Meta Llama 2 7B - 7Bパラメータ版。バランスの取れた性能を提供します。".to_string()),
            size: Some(3_800_000_000),
            parameters: Some(7_000_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("Meta".to_string()),
            license: Some("Llama 2 Community License".to_string()),
            tags: Some(r#"["chat", "general", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "llama2:13b".to_string(),
            description: Some("Meta Llama 2 13B - 13Bパラメータ版。より高い性能を提供します。".to_string()),
            size: Some(7_300_000_000),
            parameters: Some(13_000_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("Meta".to_string()),
            license: Some("Llama 2 Community License".to_string()),
            tags: Some(r#"["chat", "general", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        
        // Gemma シリーズ
        ModelCatalog {
            name: "gemma".to_string(),
            description: Some("Google Gemma - Googleが開発した軽量で高性能なオープンソースモデル。".to_string()),
            size: Some(2_000_000_000),
            parameters: Some(2_000_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("Google".to_string()),
            license: Some("Gemma Terms of Use".to_string()),
            tags: Some(r#"["chat", "general", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "gemma:2b".to_string(),
            description: Some("Google Gemma 2B - 2Bパラメータ版。軽量で高速です。".to_string()),
            size: Some(2_000_000_000),
            parameters: Some(2_000_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("Google".to_string()),
            license: Some("Gemma Terms of Use".to_string()),
            tags: Some(r#"["chat", "general", "lightweight", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "gemma:7b".to_string(),
            description: Some("Google Gemma 7B - 7Bパラメータ版。より高い性能を提供します。".to_string()),
            size: Some(4_500_000_000),
            parameters: Some(7_000_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("Google".to_string()),
            license: Some("Gemma Terms of Use".to_string()),
            tags: Some(r#"["chat", "general", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        
        // Neural Chat シリーズ
        ModelCatalog {
            name: "neural-chat".to_string(),
            description: Some("Neural Chat - 会話に最適化されたモデル。自然な対話を生成します。".to_string()),
            size: Some(4_100_000_000),
            parameters: Some(7_000_000_000),
            category: Some("chat".to_string()),
            recommended: false,
            author: Some("Intel".to_string()),
            license: Some("Apache 2.0".to_string()),
            tags: Some(r#"["chat", "conversation"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        
        // Starling シリーズ
        ModelCatalog {
            name: "starling-lm".to_string(),
            description: Some("Starling-LM - 強化学習で最適化された会話モデル。".to_string()),
            size: Some(4_100_000_000),
            parameters: Some(7_000_000_000),
            category: Some("chat".to_string()),
            recommended: false,
            author: Some("Berkeley Function Calling Leaderboard".to_string()),
            license: Some("CC-BY-NC-4.0".to_string()),
            tags: Some(r#"["chat", "conversation"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        
        // Llama 3.1 シリーズ
        ModelCatalog {
            name: "llama3.1".to_string(),
            description: Some("Meta Llama 3.1 - Llama 3の改良版。より高い性能と精度を提供します。".to_string()),
            size: Some(4_800_000_000),
            parameters: Some(8_000_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("Meta".to_string()),
            license: Some("Llama 3.1 Community License".to_string()),
            tags: Some(r#"["chat", "general", "recommended", "latest"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "llama3.1:8b".to_string(),
            description: Some("Meta Llama 3.1 8B - 8Bパラメータ版。最新の改良版です。".to_string()),
            size: Some(4_800_000_000),
            parameters: Some(8_000_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("Meta".to_string()),
            license: Some("Llama 3.1 Community License".to_string()),
            tags: Some(r#"["chat", "general", "recommended", "latest"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "llama3.1:70b".to_string(),
            description: Some("Meta Llama 3.1 70B - 70Bパラメータ版。最高レベルの性能を提供します。".to_string()),
            size: Some(40_800_000_000),
            parameters: Some(70_000_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("Meta".to_string()),
            license: Some("Llama 3.1 Community License".to_string()),
            tags: Some(r#"["chat", "general", "recommended", "latest"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "llama3.1:405b".to_string(),
            description: Some("Meta Llama 3.1 405B - 超大規模モデル。最高レベルの性能を提供します。".to_string()),
            size: Some(230_000_000_000),
            parameters: Some(405_000_000_000),
            category: Some("chat".to_string()),
            recommended: false,
            author: Some("Meta".to_string()),
            license: Some("Llama 3.1 Community License".to_string()),
            tags: Some(r#"["chat", "general", "large"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        
        // Llama 3.2 シリーズ
        ModelCatalog {
            name: "llama3.2".to_string(),
            description: Some("Meta Llama 3.2 - 最新のLlama 3.2シリーズ。".to_string()),
            size: Some(2_000_000_000),
            parameters: Some(3_000_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("Meta".to_string()),
            license: Some("Llama 3.2 Community License".to_string()),
            tags: Some(r#"["chat", "general", "recommended", "latest"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "llama3.2:1b".to_string(),
            description: Some("Meta Llama 3.2 1B - 超軽量版。モバイルデバイスでも動作可能です。".to_string()),
            size: Some(1_300_000_000),
            parameters: Some(1_000_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("Meta".to_string()),
            license: Some("Llama 3.2 Community License".to_string()),
            tags: Some(r#"["chat", "general", "lightweight", "recommended", "latest"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "llama3.2:3b".to_string(),
            description: Some("Meta Llama 3.2 3B - 軽量で高性能な3Bパラメータ版。".to_string()),
            size: Some(2_000_000_000),
            parameters: Some(3_000_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("Meta".to_string()),
            license: Some("Llama 3.2 Community License".to_string()),
            tags: Some(r#"["chat", "general", "recommended", "latest"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        
        // Qwen シリーズ
        ModelCatalog {
            name: "qwen".to_string(),
            description: Some("Qwen - Alibaba Cloudが開発した高性能な多言語モデル。".to_string()),
            size: Some(4_400_000_000),
            parameters: Some(7_000_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("Alibaba Cloud".to_string()),
            license: Some("Apache 2.0".to_string()),
            tags: Some(r#"["chat", "general", "multilingual", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "qwen:7b".to_string(),
            description: Some("Qwen 7B - 7Bパラメータ版。多言語対応で高性能です。".to_string()),
            size: Some(4_400_000_000),
            parameters: Some(7_000_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("Alibaba Cloud".to_string()),
            license: Some("Apache 2.0".to_string()),
            tags: Some(r#"["chat", "general", "multilingual", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "qwen:14b".to_string(),
            description: Some("Qwen 14B - 14Bパラメータ版。より高い性能を提供します。".to_string()),
            size: Some(8_000_000_000),
            parameters: Some(14_000_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("Alibaba Cloud".to_string()),
            license: Some("Apache 2.0".to_string()),
            tags: Some(r#"["chat", "general", "multilingual", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "qwen:32b".to_string(),
            description: Some("Qwen 32B - 32Bパラメータ版。最高レベルの性能を提供します。".to_string()),
            size: Some(18_000_000_000),
            parameters: Some(32_000_000_000),
            category: Some("chat".to_string()),
            recommended: false,
            author: Some("Alibaba Cloud".to_string()),
            license: Some("Apache 2.0".to_string()),
            tags: Some(r#"["chat", "general", "multilingual"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "qwen2".to_string(),
            description: Some("Qwen2 - Qwenの次世代版。より高い性能を提供します。".to_string()),
            size: Some(4_400_000_000),
            parameters: Some(7_000_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("Alibaba Cloud".to_string()),
            license: Some("Apache 2.0".to_string()),
            tags: Some(r#"["chat", "general", "multilingual", "recommended", "latest"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "qwen2:7b".to_string(),
            description: Some("Qwen2 7B - 7Bパラメータ版。最新の改良版です。".to_string()),
            size: Some(4_400_000_000),
            parameters: Some(7_000_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("Alibaba Cloud".to_string()),
            license: Some("Apache 2.0".to_string()),
            tags: Some(r#"["chat", "general", "multilingual", "recommended", "latest"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "qwen2.5".to_string(),
            description: Some("Qwen2.5 - Qwen2の最新版。さらに改良された性能を提供します。".to_string()),
            size: Some(4_400_000_000),
            parameters: Some(7_000_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("Alibaba Cloud".to_string()),
            license: Some("Apache 2.0".to_string()),
            tags: Some(r#"["chat", "general", "multilingual", "recommended", "latest"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "qwen2.5:7b".to_string(),
            description: Some("Qwen2.5 7B - 7Bパラメータ版。最新の改良版です。".to_string()),
            size: Some(4_400_000_000),
            parameters: Some(7_000_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("Alibaba Cloud".to_string()),
            license: Some("Apache 2.0".to_string()),
            tags: Some(r#"["chat", "general", "multilingual", "recommended", "latest"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "qwen2.5:14b".to_string(),
            description: Some("Qwen2.5 14B - 14Bパラメータ版。より高い性能を提供します。".to_string()),
            size: Some(8_000_000_000),
            parameters: Some(14_000_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("Alibaba Cloud".to_string()),
            license: Some("Apache 2.0".to_string()),
            tags: Some(r#"["chat", "general", "multilingual", "recommended", "latest"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "qwen2.5:32b".to_string(),
            description: Some("Qwen2.5 32B - 32Bパラメータ版。最高レベルの性能を提供します。".to_string()),
            size: Some(18_000_000_000),
            parameters: Some(32_000_000_000),
            category: Some("chat".to_string()),
            recommended: false,
            author: Some("Alibaba Cloud".to_string()),
            license: Some("Apache 2.0".to_string()),
            tags: Some(r#"["chat", "general", "multilingual", "latest"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "qwen2.5:72b".to_string(),
            description: Some("Qwen2.5 72B - 72Bパラメータ版。超大規模モデルです。".to_string()),
            size: Some(41_000_000_000),
            parameters: Some(72_000_000_000),
            category: Some("chat".to_string()),
            recommended: false,
            author: Some("Alibaba Cloud".to_string()),
            license: Some("Apache 2.0".to_string()),
            tags: Some(r#"["chat", "general", "multilingual", "large", "latest"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        
        // DeepSeek シリーズ
        ModelCatalog {
            name: "deepseek-coder".to_string(),
            description: Some("DeepSeek Coder - コード生成に特化した高性能モデル。".to_string()),
            size: Some(3_800_000_000),
            parameters: Some(7_000_000_000),
            category: Some("code".to_string()),
            recommended: true,
            author: Some("DeepSeek".to_string()),
            license: Some("DeepSeek License".to_string()),
            tags: Some(r#"["code", "programming", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "deepseek-coder:6.7b".to_string(),
            description: Some("DeepSeek Coder 6.7B - コード生成に特化した6.7Bパラメータ版。".to_string()),
            size: Some(3_800_000_000),
            parameters: Some(6_700_000_000),
            category: Some("code".to_string()),
            recommended: true,
            author: Some("DeepSeek".to_string()),
            license: Some("DeepSeek License".to_string()),
            tags: Some(r#"["code", "programming", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "deepseek-coder:33b".to_string(),
            description: Some("DeepSeek Coder 33B - コード生成に特化した33Bパラメータ版。".to_string()),
            size: Some(19_000_000_000),
            parameters: Some(33_000_000_000),
            category: Some("code".to_string()),
            recommended: false,
            author: Some("DeepSeek".to_string()),
            license: Some("DeepSeek License".to_string()),
            tags: Some(r#"["code", "programming"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "deepseek-chat".to_string(),
            description: Some("DeepSeek Chat - 高性能な会話モデル。".to_string()),
            size: Some(4_100_000_000),
            parameters: Some(7_000_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("DeepSeek".to_string()),
            license: Some("DeepSeek License".to_string()),
            tags: Some(r#"["chat", "general", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "deepseek-chat:6.7b".to_string(),
            description: Some("DeepSeek Chat 6.7B - 6.7Bパラメータ版。".to_string()),
            size: Some(4_100_000_000),
            parameters: Some(6_700_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("DeepSeek".to_string()),
            license: Some("DeepSeek License".to_string()),
            tags: Some(r#"["chat", "general", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "deepseek-r1".to_string(),
            description: Some("DeepSeek R1 - 推論に最適化されたモデル。".to_string()),
            size: Some(4_100_000_000),
            parameters: Some(7_000_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("DeepSeek".to_string()),
            license: Some("DeepSeek License".to_string()),
            tags: Some(r#"["chat", "reasoning", "recommended", "latest"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "deepseek-r1:7b".to_string(),
            description: Some("DeepSeek R1 7B - 推論に最適化された7Bパラメータ版。".to_string()),
            size: Some(4_100_000_000),
            parameters: Some(7_000_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("DeepSeek".to_string()),
            license: Some("DeepSeek License".to_string()),
            tags: Some(r#"["chat", "reasoning", "recommended", "latest"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        
        // Mixtral シリーズ
        ModelCatalog {
            name: "mixtral".to_string(),
            description: Some("Mixtral 8x7B - 8つのエキスパートモデルを組み合わせた高性能モデル。".to_string()),
            size: Some(26_000_000_000),
            parameters: Some(47_000_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("Mistral AI".to_string()),
            license: Some("Apache 2.0".to_string()),
            tags: Some(r#"["chat", "general", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "mixtral:8x7b".to_string(),
            description: Some("Mixtral 8x7B - 8つのエキスパートモデルを組み合わせた高性能モデル。".to_string()),
            size: Some(26_000_000_000),
            parameters: Some(47_000_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("Mistral AI".to_string()),
            license: Some("Apache 2.0".to_string()),
            tags: Some(r#"["chat", "general", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "mixtral:8x22b".to_string(),
            description: Some("Mixtral 8x22B - 超大規模な8x22Bパラメータ版。".to_string()),
            size: Some(90_000_000_000),
            parameters: Some(176_000_000_000),
            category: Some("chat".to_string()),
            recommended: false,
            author: Some("Mistral AI".to_string()),
            license: Some("Apache 2.0".to_string()),
            tags: Some(r#"["chat", "general", "large"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        
        // Mistral シリーズ（追加）
        ModelCatalog {
            name: "mistral:7b-instruct".to_string(),
            description: Some("Mistral 7B Instruct - 指示に従うことに最適化されたモデル。".to_string()),
            size: Some(4_100_000_000),
            parameters: Some(7_000_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("Mistral AI".to_string()),
            license: Some("Apache 2.0".to_string()),
            tags: Some(r#"["chat", "instruction", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "mistral-nemo".to_string(),
            description: Some("Mistral Nemo - NVIDIAとMistral AIが共同開発したモデル。".to_string()),
            size: Some(4_100_000_000),
            parameters: Some(7_000_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("NVIDIA & Mistral AI".to_string()),
            license: Some("Apache 2.0".to_string()),
            tags: Some(r#"["chat", "general", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "mistral-nemo:12b".to_string(),
            description: Some("Mistral Nemo 12B - 12Bパラメータ版。".to_string()),
            size: Some(7_000_000_000),
            parameters: Some(12_000_000_000),
            category: Some("chat".to_string()),
            recommended: true,
            author: Some("NVIDIA & Mistral AI".to_string()),
            license: Some("Apache 2.0".to_string()),
            tags: Some(r#"["chat", "general", "recommended"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        
        // Command R+ シリーズ
        ModelCatalog {
            name: "command-r".to_string(),
            description: Some("Command R - Cohereが開発した高性能な多言語モデル。".to_string()),
            size: Some(7_000_000_000),
            parameters: Some(7_000_000_000),
            category: Some("chat".to_string()),
            recommended: false,
            author: Some("Cohere".to_string()),
            license: Some("Cohere Command R License".to_string()),
            tags: Some(r#"["chat", "general", "multilingual"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "command-r-plus".to_string(),
            description: Some("Command R+ - Cohereが開発した高性能な多言語モデル（改良版）。".to_string()),
            size: Some(7_000_000_000),
            parameters: Some(7_000_000_000),
            category: Some("chat".to_string()),
            recommended: false,
            author: Some("Cohere".to_string()),
            license: Some("Cohere Command R+ License".to_string()),
            tags: Some(r#"["chat", "general", "multilingual"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        
        // Aya シリーズ
        ModelCatalog {
            name: "aya".to_string(),
            description: Some("Aya - Cohereが開発した多言語モデル。100以上の言語をサポートします。".to_string()),
            size: Some(4_100_000_000),
            parameters: Some(7_000_000_000),
            category: Some("chat".to_string()),
            recommended: false,
            author: Some("Cohere".to_string()),
            license: Some("Cohere Aya License".to_string()),
            tags: Some(r#"["chat", "general", "multilingual"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "aya:8b".to_string(),
            description: Some("Aya 8B - 8Bパラメータ版。100以上の言語をサポートします。".to_string()),
            size: Some(4_700_000_000),
            parameters: Some(8_000_000_000),
            category: Some("chat".to_string()),
            recommended: false,
            author: Some("Cohere".to_string()),
            license: Some("Cohere Aya License".to_string()),
            tags: Some(r#"["chat", "general", "multilingual"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        
        // Granite シリーズ
        ModelCatalog {
            name: "granite-code".to_string(),
            description: Some("Granite Code - IBMが開発したコード生成モデル。".to_string()),
            size: Some(3_800_000_000),
            parameters: Some(7_000_000_000),
            category: Some("code".to_string()),
            recommended: false,
            author: Some("IBM".to_string()),
            license: Some("Apache 2.0".to_string()),
            tags: Some(r#"["code", "programming"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "granite-code:8b".to_string(),
            description: Some("Granite Code 8B - 8Bパラメータ版。コード生成に特化しています。".to_string()),
            size: Some(4_700_000_000),
            parameters: Some(8_000_000_000),
            category: Some("code".to_string()),
            recommended: false,
            author: Some("IBM".to_string()),
            license: Some("Apache 2.0".to_string()),
            tags: Some(r#"["code", "programming"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        
        // Solar シリーズ
        ModelCatalog {
            name: "solar".to_string(),
            description: Some("Solar - Upstageが開発した高性能なモデル。".to_string()),
            size: Some(4_100_000_000),
            parameters: Some(7_000_000_000),
            category: Some("chat".to_string()),
            recommended: false,
            author: Some("Upstage".to_string()),
            license: Some("Apache 2.0".to_string()),
            tags: Some(r#"["chat", "general"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "solar:10.7b".to_string(),
            description: Some("Solar 10.7B - 10.7Bパラメータ版。".to_string()),
            size: Some(6_000_000_000),
            parameters: Some(10_700_000_000),
            category: Some("chat".to_string()),
            recommended: false,
            author: Some("Upstage".to_string()),
            license: Some("Apache 2.0".to_string()),
            tags: Some(r#"["chat", "general"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        
        // TinyLlama シリーズ
        ModelCatalog {
            name: "tinyllama".to_string(),
            description: Some("TinyLlama - 超軽量な1.1Bパラメータモデル。リソースが限られた環境でも動作します。".to_string()),
            size: Some(637_000_000),
            parameters: Some(1_100_000_000),
            category: Some("chat".to_string()),
            recommended: false,
            author: Some("TinyLlama Team".to_string()),
            license: Some("Apache 2.0".to_string()),
            tags: Some(r#"["chat", "general", "lightweight"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        
        // Nous Hermes シリーズ
        ModelCatalog {
            name: "nous-hermes2".to_string(),
            description: Some("Nous Hermes 2 - 会話に最適化されたモデル。".to_string()),
            size: Some(4_100_000_000),
            parameters: Some(7_000_000_000),
            category: Some("chat".to_string()),
            recommended: false,
            author: Some("Nous Research".to_string()),
            license: Some("Apache 2.0".to_string()),
            tags: Some(r#"["chat", "conversation"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "nous-hermes2:mixtral".to_string(),
            description: Some("Nous Hermes 2 Mixtral - Mixtralベースの会話モデル。".to_string()),
            size: Some(26_000_000_000),
            parameters: Some(47_000_000_000),
            category: Some("chat".to_string()),
            recommended: false,
            author: Some("Nous Research".to_string()),
            license: Some("Apache 2.0".to_string()),
            tags: Some(r#"["chat", "conversation"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        
        // Dolphin シリーズ
        ModelCatalog {
            name: "dolphin-mixtral".to_string(),
            description: Some("Dolphin Mixtral - 会話に最適化されたMixtralベースのモデル。".to_string()),
            size: Some(26_000_000_000),
            parameters: Some(47_000_000_000),
            category: Some("chat".to_string()),
            recommended: false,
            author: Some("Cognitive Computations".to_string()),
            license: Some("Apache 2.0".to_string()),
            tags: Some(r#"["chat", "conversation"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "dolphin-llama3".to_string(),
            description: Some("Dolphin Llama 3 - Llama 3ベースの会話モデル。".to_string()),
            size: Some(4_700_000_000),
            parameters: Some(8_000_000_000),
            category: Some("chat".to_string()),
            recommended: false,
            author: Some("Cognitive Computations".to_string()),
            license: Some("Apache 2.0".to_string()),
            tags: Some(r#"["chat", "conversation"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        
        // OpenChat シリーズ
        ModelCatalog {
            name: "openchat".to_string(),
            description: Some("OpenChat - オープンソースの会話モデル。".to_string()),
            size: Some(4_100_000_000),
            parameters: Some(7_000_000_000),
            category: Some("chat".to_string()),
            recommended: false,
            author: Some("OpenChat Team".to_string()),
            license: Some("Apache 2.0".to_string()),
            tags: Some(r#"["chat", "conversation"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "openchat:7b".to_string(),
            description: Some("OpenChat 7B - 7Bパラメータ版。".to_string()),
            size: Some(4_100_000_000),
            parameters: Some(7_000_000_000),
            category: Some("chat".to_string()),
            recommended: false,
            author: Some("OpenChat Team".to_string()),
            license: Some("Apache 2.0".to_string()),
            tags: Some(r#"["chat", "conversation"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        
        // WizardLM シリーズ
        ModelCatalog {
            name: "wizardlm2".to_string(),
            description: Some("WizardLM 2 - 複雑なタスクに優れた性能を発揮するモデル。".to_string()),
            size: Some(4_100_000_000),
            parameters: Some(7_000_000_000),
            category: Some("chat".to_string()),
            recommended: false,
            author: Some("WizardLM Team".to_string()),
            license: Some("Apache 2.0".to_string()),
            tags: Some(r#"["chat", "general"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "wizardlm2:8x22b".to_string(),
            description: Some("WizardLM 2 8x22B - 超大規模な8x22Bパラメータ版。".to_string()),
            size: Some(90_000_000_000),
            parameters: Some(176_000_000_000),
            category: Some("chat".to_string()),
            recommended: false,
            author: Some("WizardLM Team".to_string()),
            license: Some("Apache 2.0".to_string()),
            tags: Some(r#"["chat", "general", "large"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        
        // Yi シリーズ
        ModelCatalog {
            name: "yi".to_string(),
            description: Some("Yi - 01.AIが開発した高性能な多言語モデル。".to_string()),
            size: Some(4_100_000_000),
            parameters: Some(7_000_000_000),
            category: Some("chat".to_string()),
            recommended: false,
            author: Some("01.AI".to_string()),
            license: Some("Yi License".to_string()),
            tags: Some(r#"["chat", "general", "multilingual"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "yi:6b".to_string(),
            description: Some("Yi 6B - 6Bパラメータ版。".to_string()),
            size: Some(3_500_000_000),
            parameters: Some(6_000_000_000),
            category: Some("chat".to_string()),
            recommended: false,
            author: Some("01.AI".to_string()),
            license: Some("Yi License".to_string()),
            tags: Some(r#"["chat", "general", "multilingual"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "yi:34b".to_string(),
            description: Some("Yi 34B - 34Bパラメータ版。".to_string()),
            size: Some(19_000_000_000),
            parameters: Some(34_000_000_000),
            category: Some("chat".to_string()),
            recommended: false,
            author: Some("01.AI".to_string()),
            license: Some("Yi License".to_string()),
            tags: Some(r#"["chat", "general", "multilingual"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        
        // Nemotron シリーズ
        ModelCatalog {
            name: "nemotron".to_string(),
            description: Some("Nemotron - NVIDIAが開発した高性能なモデル。".to_string()),
            size: Some(4_100_000_000),
            parameters: Some(7_000_000_000),
            category: Some("chat".to_string()),
            recommended: false,
            author: Some("NVIDIA".to_string()),
            license: Some("Nemotron License".to_string()),
            tags: Some(r#"["chat", "general"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        
        // LLaVA シリーズ（マルチモーダル）
        ModelCatalog {
            name: "llava".to_string(),
            description: Some("LLaVA - 画像とテキストの両方を理解できるマルチモーダルモデル。".to_string()),
            size: Some(4_700_000_000),
            parameters: Some(8_000_000_000),
            category: Some("other".to_string()),
            recommended: false,
            author: Some("LLaVA Team".to_string()),
            license: Some("Apache 2.0".to_string()),
            tags: Some(r#"["multimodal", "vision", "chat"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "llava:7b".to_string(),
            description: Some("LLaVA 7B - 7Bパラメータ版。画像とテキストの両方を理解できます。".to_string()),
            size: Some(4_100_000_000),
            parameters: Some(7_000_000_000),
            category: Some("other".to_string()),
            recommended: false,
            author: Some("LLaVA Team".to_string()),
            license: Some("Apache 2.0".to_string()),
            tags: Some(r#"["multimodal", "vision", "chat"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "llava:13b".to_string(),
            description: Some("LLaVA 13B - 13Bパラメータ版。より高い性能を提供します。".to_string()),
            size: Some(7_300_000_000),
            parameters: Some(13_000_000_000),
            category: Some("other".to_string()),
            recommended: false,
            author: Some("LLaVA Team".to_string()),
            license: Some("Apache 2.0".to_string()),
            tags: Some(r#"["multimodal", "vision", "chat"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        
        // BakLLaVA シリーズ
        ModelCatalog {
            name: "bakllava".to_string(),
            description: Some("BakLLaVA - 軽量なマルチモーダルモデル。".to_string()),
            size: Some(4_100_000_000),
            parameters: Some(7_000_000_000),
            category: Some("other".to_string()),
            recommended: false,
            author: Some("BakLLaVA Team".to_string()),
            license: Some("Apache 2.0".to_string()),
            tags: Some(r#"["multimodal", "vision", "chat"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        
        // Nomic Embed シリーズ
        ModelCatalog {
            name: "nomic-embed".to_string(),
            description: Some("Nomic Embed - テキスト埋め込み生成に特化したモデル。".to_string()),
            size: Some(274_000_000),
            parameters: Some(137_000_000),
            category: Some("other".to_string()),
            recommended: false,
            author: Some("Nomic".to_string()),
            license: Some("Apache 2.0".to_string()),
            tags: Some(r#"["embedding", "text"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        ModelCatalog {
            name: "nomic-embed-text".to_string(),
            description: Some("Nomic Embed Text - テキスト埋め込み生成に特化したモデル。".to_string()),
            size: Some(274_000_000),
            parameters: Some(137_000_000),
            category: Some("other".to_string()),
            recommended: false,
            author: Some("Nomic".to_string()),
            license: Some("Apache 2.0".to_string()),
            tags: Some(r#"["embedding", "text"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        
        // MXBai シリーズ
        ModelCatalog {
            name: "mxbai-embed-large".to_string(),
            description: Some("MXBai Embed Large - 大規模な埋め込み生成モデル。".to_string()),
            size: Some(1_300_000_000),
            parameters: Some(335_000_000),
            category: Some("other".to_string()),
            recommended: false,
            author: Some("Mixed Bread AI".to_string()),
            license: Some("Apache 2.0".to_string()),
            tags: Some(r#"["embedding", "text"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        
        // BGE シリーズ
        ModelCatalog {
            name: "bge-large".to_string(),
            description: Some("BGE Large - 高性能な埋め込み生成モデル。".to_string()),
            size: Some(1_300_000_000),
            parameters: Some(335_000_000),
            category: Some("other".to_string()),
            recommended: false,
            author: Some("BAAI".to_string()),
            license: Some("MIT".to_string()),
            tags: Some(r#"["embedding", "text"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
        
        // E5 シリーズ
        ModelCatalog {
            name: "e5-large-v2".to_string(),
            description: Some("E5 Large v2 - 高性能な埋め込み生成モデル。".to_string()),
            size: Some(560_000_000),
            parameters: Some(335_000_000),
            category: Some("other".to_string()),
            recommended: false,
            author: Some("Microsoft".to_string()),
            license: Some("MIT".to_string()),
            tags: Some(r#"["embedding", "text"]"#.to_string()),
            created_at: now,
            updated_at: now,
        },
    ]
}


